### ISSUE TITLE
Idea 01

### ISSUE THREAD

**Issue by aaspee-github** [aaspee-github/React-my-app#1]
Muestra la ubicación para cada movimiento en el formato (columna, fila) en la lista del historial de movimientos.

**Comment by aaspee01** [comment]
Esta todavía activo este requerimiento?

**Comment by aaspee-github** [comment]
Si.. puedes hacerlo?

**Comment by aaspee-github** [comment]
> Esta todavía activo este requerimiento?

Si.. puedes hacerlo?

**Comment by aaspee-github** [comment]
> Esta todavía activo este requerimiento?

cuanto tiempo te tomaria?

**Comment by aaspee01** [comment]
creo que un dia..

**Comment by aaspee-github** [comment]
ok..

**Comment by aaspee-github** [comment]
Idea 01 lista. Se cierra
